name: Setup Maven wrapper Cache
description: |
  Setup the Maven wrapper cache for mvnw.

inputs:
  MAVEN_WRAPPER_DIR:
    description: |
      The path to the Maven wrapper directory for caching.
    required: false

runs:
  using: composite
  steps:
    - name: Cache wrapper directory
      if: ${{ inputs.MAVEN_WRAPPER_DIR != '' }}
      uses: actions/cache@v4
      with:
        path: ${{ inputs.MAVEN_WRAPPER_DIR }}
        key: ${{ runner.os }}-${{ inputs.MAVEN_WRAPPER_DIR }}-${{ hashFiles('.mvn/wrapper/maven-wrapper.properties') }}
