name: Replace all variables in the docs
description: |
  Replace all variables in the docs

inputs:
  VERSION:
    description: |
      The current version

runs:
  using: composite
  steps:
    - name: Set CHANGELOG.md version
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        sed -i "s~## \[Unreleased\]~## \[${VERSION}\]~g" ./CHANGELOG.md
        DATE="$(date +%Y-%m-%d)"
        sed -i "s~\${maven\.build\.timestamp}~$DATE~g" ./CHANGELOG.md
        echo "$(cat ./CHANGELOG.md)" >> './docs/Documentation/CHANGELOG.md'
      env:
        VERSION: ${{ inputs.VERSION }}
    - name: Set user feedback form version in mkdocs.yml
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        sed -i "s~%VERSION%~${VERSION}~g" ./mkdocs.yml
      env:
        VERSION: ${{ inputs.VERSION }}
