name: Setup MkDocs Material
description: |
  This action sets up a Python environment with the latest version of
  MkDocs Material and its dependencies and optionally caches the build.

inputs:
  MKDOCS_SITE_DIR:
    description: |
      The path to the MkDocs site directory for caching.
    required: false
  PYTHON_VERSION:
    description: |
      The version of Python to use.
    required: false
    default: '3.10'
  PYTHON_CACHE:
    description: |
      The name of the Python cache to use.
    required: false
  PYTHON_CACHE_DEPENDENCY_PATH:
    description: |
      The path to the Python cache dependency.
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        cache: ${{ inputs.PYTHON_CACHE }}
        cache-dependency-path: ${{ inputs.PYTHON_CACHE_DEPENDENCY_PATH }}
    - uses: BetonQuest/Workflows/.github/actions/setup-mkdocs-material/cache@main
      with:
        MKDOCS_SITE_DIR: ${{ inputs.MKDOCS_SITE_DIR }}
    - name: Cache MkDocs site directory /.cache/plugins/optimize
      if: ${{ inputs.MKDOCS_SITE_DIR != '' }}
      uses: actions/cache@v4
      with:
        path: ${{ inputs.MKDOCS_SITE_DIR }}/.cache/plugins/optimize
        key: ${{ runner.os }}-hardcoded-media-cache
    - name: Install pngquant, a CI only dependency for mkdocs-material image optimization
      uses: awalsh128/cache-apt-pkgs-action@v1.4.3
      with:
        packages: pngquant
    - name: Update python pip
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        python3 -m pip install --upgrade pip
    - name: Install dependencies with pip install
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        pip install ./docs[imaging]
